
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rating_db
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: RatingMicroService
  jpa:
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8082