
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rating_db
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: Rating-MicroService
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  config:
   import: configserver:http://localhost:8083

server:
  port: 8082

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
